import 'package:flutter/cupertino.dart';

class TimeZoneList extends StatefulWidget {
  const TimeZoneList({super.key});

  @override
  State<TimeZoneList> createState() => _TimeZoneListState();
}

class _TimeZoneListState extends State<TimeZoneList> {
  List<Map<String, dynamic>> timeZones = [
    {'country': 'Ivory Coast', 'offset': 'GMT+00:00'},
    {'country': 'Ghana', 'offset': 'GMT+00:00'},
    {'country': 'Ethiopia', 'offset': 'GMT+03:00'},
    {'country': 'Algeria', 'offset': 'GMT+01:00'},
    {'country': 'Eritrea', 'offset': 'GMT+03:00'},
    {'country': 'Mali', 'offset': 'GMT+00:00'},
    {'country': 'Central African Republic', 'offset': 'GMT+01:00'},
    {'country': 'Gambia', 'offset': 'GMT+00:00'},
    {'country': 'Guinea-Bissau', 'offset': 'GMT+00:00'},
    {'country': 'Malawi', 'offset': 'GMT+02:00'},
    {'country': 'Republic of the Congo', 'offset': 'GMT+01:00'},
    {'country': 'Burundi', 'offset': 'GMT+02:00'},
    {'country': 'Egypt', 'offset': 'GMT+02:00'},
    {'country': 'Morocco', 'offset': 'GMT+01:00'},
    {'country': 'Spain', 'offset': 'GMT+02:00'},
    {'country': 'Guinea', 'offset': 'GMT+00:00'},
    {'country': 'Senegal', 'offset': 'GMT+00:00'},
    {'country': 'Tanzania', 'offset': 'GMT+03:00'},
    {'country': 'Djibouti', 'offset': 'GMT+03:00'},
    {'country': 'Cameroon', 'offset': 'GMT+01:00'},
    {'country': 'Western Sahara', 'offset': 'GMT+01:00'},
    {'country': 'Sierra Leone', 'offset': 'GMT+00:00'},
    {'country': 'Botswana', 'offset': 'GMT+02:00'},
    {'country': 'Zimbabwe', 'offset': 'GMT+02:00'},
    {'country': 'South Africa', 'offset': 'GMT+02:00'},
    {'country': 'South Sudan', 'offset': 'GMT+03:00'},
    {'country': 'Uganda', 'offset': 'GMT+03:00'},
    {'country': 'Sudan', 'offset': 'GMT+02:00'},
    {'country': 'Rwanda', 'offset': 'GMT+02:00'},
    {'country': 'Democratic Republic of the Congo', 'offset': 'GMT+01:00'},
    {'country': 'Nigeria', 'offset': 'GMT+01:00'},
    {'country': 'Gabon', 'offset': 'GMT+01:00'},
    {'country': 'Togo', 'offset': 'GMT+00:00'},
    {'country': 'Angola', 'offset': 'GMT+01:00'},
    {'country': 'Equatorial Guinea', 'offset': 'GMT+01:00'},
    {'country': 'Mozambique', 'offset': 'GMT+02:00'},
    {'country': 'Lesotho', 'offset': 'GMT+02:00'},
    {'country': 'Eswatini', 'offset': 'GMT+02:00'},
    {'country': 'Somalia', 'offset': 'GMT+03:00'},
    {'country': 'Liberia', 'offset': 'GMT+00:00'},
    {'country': 'Kenya', 'offset': 'GMT+03:00'},
    {'country': 'Chad', 'offset': 'GMT+01:00'},
    {'country': 'Niger', 'offset': 'GMT+01:00'},
    {'country': 'Mauritania', 'offset': 'GMT+00:00'},
    {'country': 'Burkina Faso', 'offset': 'GMT+00:00'},
    {'country': 'Benin', 'offset': 'GMT+01:00'},
    {'country': 'Sao Tome and Principe', 'offset': 'GMT+00:00'},
    {'country': 'Libya', 'offset': 'GMT+02:00'},
    {'country': 'Tunisia', 'offset': 'GMT+01:00'},
    {'country': 'Namibia', 'offset': 'GMT+02:00'},
    {'country': 'United States', 'offset': 'GMT-09:00'},
    {'country': 'United States', 'offset': 'GMT-08:00'},
    {'country': 'Anguilla', 'offset': 'GMT-04:00'},
    {'country': 'Antigua and Barbuda', 'offset': 'GMT-04:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Aruba', 'offset': 'GMT-04:00'},
    {'country': 'Paraguay', 'offset': 'GMT-04:00'},
    {'country': 'Canada', 'offset': 'GMT-05:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Dominica', 'offset': 'GMT-04:00'},
    {'country': 'Canada', 'offset': 'GMT-06:00'},
    {'country': 'Ecuador', 'offset': 'GMT-05:00'},
    {'country': 'Guyana', 'offset': 'GMT-04:00'},
    {'country': 'Canada', 'offset': 'GMT-03:00'},
    {'country': 'Cuba', 'offset': 'GMT-04:00'},
    {'country': 'Grenada', 'offset': 'GMT-04:00'},
    {'country': 'Guadeloupe', 'offset': 'GMT-04:00'},
    {'country': 'Guatemala', 'offset': 'GMT-06:00'},
    {'country': 'Guyana', 'offset': 'GMT-04:00'},
    {'country': 'United States', 'offset': 'GMT-07:00'},
    {'country': 'Brazil', 'offset': 'GMT-04:00'},
    {'country': 'Mexico', 'offset': 'GMT-06:00'},
    {'country': 'Canada', 'offset': 'GMT-05:00'},
    {'country': 'Canada', 'offset': 'GMT-06:00'},
    {'country': 'Chile', 'offset': 'GMT-03:00'},
    {'country': 'Colombia', 'offset': 'GMT-05:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Peru', 'offset': 'GMT-05:00'},
    {'country': 'United States', 'offset': 'GMT-06:00'},
    {'country': 'Canada', 'offset': 'GMT-06:00'},
    {'country': 'United States', 'offset': 'GMT-07:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Canada', 'offset': 'GMT-05:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Brazil', 'offset': 'GMT-03:00'},
    {'country': 'Canada', 'offset': 'GMT-05:00'},
    {'country': 'Canada', 'offset': 'GMT-06:00'},
    {'country': 'Canada', 'offset': 'GMT-07:00'},
    {'country': 'Chile', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
    {'country': 'Argentina', 'offset': 'GMT-03:00'},
  ];

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
